export { default as Dashboard } from './modules/Dashboard'
export { default as Employees } from './modules/Employees'
export { default as Departments } from './modules/Departments'
export { default as Specialties } from './modules/Specialties'
export { default as OnBoardingPlanList } from './modules/OnBoardingPlanList'
export { default as OnBoardingPlanEditor } from './modules/OnboardingPlanEditor'
